void display_init();
void update_display();
void clear_display();
void display_pirds();
void display_print_line(int line, char* s);
void display_min_max_pressure(bool max_not_min);
void display_pressure();
void display_debug();
void display_oxgen();
void display_print_pirds(char e, char t, char loc, unsigned short int n, unsigned long ms, signed long val);
